Asher/change pw nextjs
CS3219-AY2223S1/cs3219-project-ay2223s1-g55 pull request #41
Opened 2022-09-14 15:22 UTC by asherhy

Closes #20

2022-09-14 18:07 UTC, glennljw commented on frontend/contexts/session.context.jsx
> +        test: res.data.test,
Can I confirm if this was just used for debugging? Will need to know cos I'm changing to zustand

2022-09-14 18:16 UTC, takufunkai requested changes

2022-09-14 18:16 UTC, takufunkai commented on user-service/index.js
> +router.put('/password', updateUser);
Could we make this a put request under the user endpoint? i.e.
`router.put('/', updateUser)`

Personally I think that this is an update on a user, so it makes sense to set the put request in the `/api/user/` endpoint instead of having a separate password endpoint.

2022-09-14 18:16 UTC, takufunkai commented on frontend/pages/change-password.tsx
> +  const [passwordError, setPasswordErr] = useState('');
I think the variable names should be consistent, for eg: `[oldPasswordError, setOldPasswordError]`

2022-09-14 18:17 UTC, takufunkai commented on frontend/pages/change-password.tsx
> +            helperText={passwordError.length > 0 ? passwordError : ''}
Just a minor comment: if passwordError === '' or undefined, you can just pass it in. For example: `error={passwordError.length}` and `helperText={passwordError ?? ''}`

2022-09-14 19:04 UTC, asherhy commented on user-service/index.js
> +router.put('/password', updateUser);
sure i was also thinking if we should follow the crud naming convention or not. We can follow this from now 
✅ GET /users: lists of all users.
✅ POST /users: creates a new user.
✅ PUT /users/{userId}: updates a user.
✅ DELETE /users/{userId}: deletes a specific user.
✅ PATCH /users/{userId}: partially updates a user.
✅ GET /users/{userId}/orders: lists of all orders for a particular user.
✅ POST /users/{userId}/cart/checkout: runs the checkout process.

2022-09-15 04:56 UTC, takufunkai commented on user-service/index.js
> +router.put('/password', updateUser);
great idea 🙏

2022-09-19 22:34 UTC, asherhy commented on frontend/pages/change-password.tsx
> +            helperText={passwordError.length > 0 ? passwordError : ''}
passwordError is a string not a boolean so it cant be changed, for the helper text I have changed it.

2022-09-20 01:28 UTC, glennljw requested changes
LGTM, just some minor nits regarding the store!

2022-09-20 01:28 UTC, glennljw commented on frontend/lib/store.ts
>    },
Okay correct me if I'm wrong, but I believe that the `updateUser` function used for changing password does not log the user out on successful change. In that case, it doesn't change the state of the user session and shouldn't be used in store. 

The purpose of the `updateUser` used in `_app.tsx` is to fetch the jwt cookies which does a `set` in the store, updating the user session.

So what I'd suggest is to abstract this function back into your component, exporting `getJwtCookies` and using it directly.

2022-09-20 11:55 UTC, glennljw approved these changes

2022-09-20 11:57 UTC, merged