Integrate question service with Match Session and Collaborative Platform Editor
CS3219-AY2223S1/cs3219-project-ay2223s1-g55 pull request #61
Opened 2022-10-17 22:10 UTC by glennljw

* [ ] Add question field for matched session, since question is selected after matching, and before entering room stage.
* [ ] Add socketId (temporary fix) to user store as means of retrieving question assigned during socket connection in match stage, will fail when socketId somehow changes, maybe when refreshing page etc.

* [ ] **TODO:** Add question to collection for editor service session

2022-10-20 14:11 UTC, takufunkai requested changes
Minor review, havent actually tried the app yet

2022-10-20 14:11 UTC, takufunkai commented on frontend/components/Question/QuestionDescription.tsx
> +  };
Probably cleaner to use an object/map instead?

2022-10-20 14:11 UTC, takufunkai commented on frontend/components/Question/QuestionDiscussion.tsx
> +          const timeStr = `${date}/${month}/${year} ${hourStr}:${minStr}`;
Instead of doing this, could we just use a library like Dayjs to handle parsing + formating of date-time?

2022-10-20 16:58 UTC, asherhy requested changes
Just some small changes. Overall looking good!

2022-10-20 16:58 UTC, asherhy commented on frontend/components/collaboration-platform/editor.tsx
> +      <QuestionDescription question={question} />
Possible to do it in another component eg under collaboration-platform folder have another question.tsx or smth. Do you think that would be better?

2022-10-20 16:58 UTC, asherhy commented on frontend/pages/match/index.tsx
> +  const [socketID, setSocketID] = useState(socket.id);
The reason why socketID was initialized to none might be because the socket.id might not be available at build time for nextjs

2022-10-20 16:58 UTC, asherhy commented on matching-service/index.js
> +router.get('/session/:sessionId', getSessionQuestion);
get: 'session/{sessionId}' tend to suggest to return a specific resource of session as per rest API naming conventions. Treat the forward slashes as hierarchy. one possible way to name it : 'sessions/:sessionId/questions' as usually resources are named plurally.

2022-10-21 00:27 UTC, glennljw commented on frontend/pages/match/index.tsx
> +  const [socketID, setSocketID] = useState(socket.id);
This was a temporary fix just to make the matching work cos it was quite buggy. I let @takufunkai know since he was taking over the matching service for front end.

2022-10-21 01:27 UTC, glennljw commented on frontend/components/collaboration-platform/editor.tsx
> +      <QuestionDescription question={question} />
Hmm personally I think it wouldn't be necessary as QuestionDescription is a reusable component from Questions, so we can just use it in this component.

2022-10-21 15:24 UTC, asherhy approved these changes
looks good!

2022-10-21 15:27 UTC, takufunkai approved these changes
LGTM LETS GET THIS BREAD

2022-10-21 15:28 UTC, merged